- GarhalController/AntiAim.cpp
- GarhalController/ClientMode.h
- GarhalController/Entity.cpp
- GarhalController/GarhalController.cpp
- GarhalController/GarhalController.vcxproj
- GarhalController/GarhalController.vcxproj.filters
- GarhalController/data.hpp
> No idea if this works, but worths a try.

- Garhal/Garhal.vcxproj
- Garhal/Garhal.vcxproj.filters
- Garhal/communication.c
- Garhal/data.h
- Garhal/events.c
- Garhal/events.h
- Garhal/garhal.c
- Garhal/garhal.h
- Garhal/hide.c
- Garhal/memory.c
- Garhal/memory.h
- Garhal/vector.c
- Garhal/vector.h
- GarhalController/CInput.h
- GarhalController/CUserCmd.h
- GarhalController/GarhalController.cpp
- GarhalController/GarhalController.vcxproj
- GarhalController/GarhalController.vcxproj.filters
- GarhalController/garhal.cfg
> OBRegisterCallback, project fixups, fixes, vectors, csrss, etc..

- GarhalController/GarhalController.cpp
- GarhalRankDisplayer/GarhalRankDisplayer.cpp
> Ok. I certainly need sleep.

- Garhal/memory.c
- GarhalController/GarhalController.cpp
- GarhalRankDisplayer/GarhalRankDisplayer.cpp
> Fixed triggerbot, and other stuff.

- GarhalController/offsets.hpp
- GarhalRankDisplayer/offsets.hpp
> Offset update.

- Garhal/events.c
- GarhalController/offsets.hpp
- GarhalRankDisplayer/offsets.hpp
> Update offsets.hpp and events.c

- Garhal/communication.c
> communication.c

- Garhal/garhal.c
- Garhal/garhal.h
- Garhal/memory.c
> Fixing windows offsets.

- Garhal/garhal.c
> Remove until testing.

- GarhalController/Matrix.hpp
> Minor addition needed according to @54wedge.

- .gitignore
- Garhal/memory.c
- GarhalController/Entity.cpp
- GarhalController/GarhalController.cpp
- GarhalController/data.hpp
- GarhalController/garhal.cfg
Adding FreeMemory for future use.
> Adding TriggerBot delay.

- Garhal/memory.c
> Handle EPROCESS failure.

- GarhalController/offsets.hpp
- GarhalRankDisplayer/offsets.hpp
> Volvo stop with the frequent updates already.

- Garhal/data.h
- Garhal/garhal.c
- GarhalController/offsets.hpp
- GarhalRankDisplayer/offsets.hpp
> offsets.hpp

- Garhal/Garhal.vcxproj
- Garhal/communication.c
- Garhal/communication.h
- Garhal/data.h
- Garhal/events.c
- GarhalController/GarhalController.cpp
- GarhalController/GarhalController.vcxproj
- GarhalController/GarhalController.vcxproj.filters
- GarhalController/communications.hpp
- GarhalController/data.hpp
- GarhalController/garhal.cfg
- GarhalController/kernelinterface.hpp
- GarhalController/offsets.hpp
- GarhalRankDisplayer/communications.hpp
- GarhalRankDisplayer/kernelinterface.hpp
- GarhalRankDisplayer/offsets.hpp
Better way of handling OBRegisterCallback flags.
> Bunch of changes, refactoring.

- GarhalRankDisplayer/GarhalRankDisplayer.cpp
> Change behaviour.

- Garhal/communication.c
- Garhal/garhal.c
> Manual map update.

- GarhalController/Matrix.hpp
> Algorithm include for newbies.

- Garhal/Garhal.vcxproj
> That's supposed to stay.

- GarhalController/Aimbot.cpp
> Little update.

- Garhal/garhal.c
- GarhalController/GarhalController.cpp
- GarhalController/offsets.hpp
> That's supposed to be commented.

- Garhal/memory.c
- GarhalController/offsets.hpp
- GarhalRankDisplayer/offsets.hpp
> Offset & 2009

- GarhalController/Entity.cpp
> glow object fix

- Garhal/memory.c
- README.md
Fully tested & working on Windows 21H2 build 19044
> Support for windows 2110/21H2
